#ifndef CD_SPRINGYKEYS_SYMBOLS_H__
#define CD_SPRINGYKEYS_SYMBOLS_H__

enum
{
	IDS_CDSPRNGKYS   = 10000,
	IDS_STIFFNESS,
	IDS_DAMPING,
	IDS_MASS,
	IDS_POS_FORCES,
	IDS_SCA_FORCES,
	IDS_ROT_FORCES,
	IDS_POSITION_FORCES,
	IDS_TAG_NAME,
	IDS_CMD_BAKE_ALL,
	IDS_CMD_UNBAKE_ALL,
	IDS_STATUS_BAKE_SAMPLING,
	IDS_STATUS_BAKE_WRITING,
	IDS_MSG_DESC_LOAD_FAILED,
	IDS_MSG_BAKE_ALL_NONE,
	IDS_MSG_BAKE_ALL_DONE,
	IDS_MSG_BAKE_ALL_SKIPPED,
	IDS_MSG_UNBAKE_ALL_NONE,
	IDS_MSG_UNBAKE_ALL_DONE,
	IDS_MSG_UNBAKE_ALL_NOTE,
	IDS_MSG_BAKE_NEED_HOST,
	IDS_MSG_BAKE_ALREADY_LOCKED,
	IDS_MSG_BAKE_FAILED,
	IDS_MSG_BAKE_DONE,
	IDS_MSG_BAKE_FRAME_RANGE,
	IDS_MSG_BAKE_LOCK_NOTICE,
	IDS_MSG_UNBAKE_NO_BACKUP,
	IDS_MSG_UNBAKE_FAILED,
	IDS_MSG_UNBAKE_DONE,
	IDS_MSG_REGISTER_TAG_FAILED,
	IDS_MSG_REGISTER_CMD_FAILED,
	_DUMMY_ELEMENT_
};

#endif
